### ISSUE TITLE
Hiding the GUI

### ISSUE THREAD

**Issue by jes3d** [biosignalsplux/unity-sample#11]
nevermind, solved the issue 

The Canvas object and the render component are both named "canvas" so I believe my script was adressing the object instead of the renderer

**Comment by GRamosPlux** [comment]
Dear @jes3d,

Thank you very much for being part of our enthusiastic community of users and for opening this new issue!
We are really glad for understanding that you were able to overtake the original obstacle.

Please, do not hesitate to create a new issue if any new question about the **PLUX Unity API** arises.

For now, let me wish you a continuation of an excellent work full of exciting discoveries.

**My best and sincere regards,**
@GRamosPlux
